apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs-container
        image: ghcr.io/prince730-creator/project:latest
        ports:
        - containerPort: 3000
        # Optional: environment variables
        env:
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: NodePort   # For local testing, can change to LoadBalancer in cloud
  selector:
    app: nextjs
  ports:
  - protocol: TCP
    port: 3000        # Container port
    targetPort: 3000  # Container port inside pod
    nodePort: 30001   # Host port on node, pick free port
